In [14]:
import torch
a = {0: [1], 1: [2, 3, 4, 5], 2: [6, 7, 8, 9], 3: [10, 11, 12, 13], 4: [14, 15], 5: [16], 6: [18], 10: [19], 16: [17], 17: [20], 19: [21], 20: [22], 21: [23]}

In [1]:
data = [0,1,2,3]

In [2]:
data[-1]

3

In [17]:
l = [sub_list + [0]*(4 - len(sub_list)) for sub_list in list(a.values())]

In [50]:
import torch

# 创建一个示例二维Tensor
tensor = torch.tensor([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])

# 定义每一行需要的数据位置，并填充使得形状一致
indices = torch.tensor([
    [0, 1],  # 第一行需要第2和第4个元素，填充-1
    [2,3],  # 第二行需要第1、第3和第5个元素
    [3,4]  # 第三行需要第2和第3个元素，填充-1
])

# 获取行索引
row_indices = torch.arange(tensor.size(0)).unsqueeze(1).expand_as(indices)

# 使用高级索引获取每一行指定位置的数据
selected_data = tensor[row_indices, indices]
selected_data[indices == -1] = 0  # 将填充位置的值设为0

print(selected_data)

tensor([[ 1,  2],
        [ 8,  9],
        [14, 15]])


In [60]:
data = torch.arange(4).reshape(4,1)

In [67]:
data.view(-1).gt(0)

tensor([False,  True,  True,  True])

In [69]:
torch.nonzero(data.view(-1).gt(0)).view(-1)

tensor([1, 2, 3])

In [53]:
row_indices>1

tensor([[False, False],
        [False, False],
        [ True,  True]])

In [54]:
positions = torch.nonzero(row_indices>1)

In [8]:
data = {1,2,3,4}

In [12]:
data.add(0)

In [13]:
data

{0, 1, 2, 3, 4}

In [2]:
from transformers import AutoModelForCausalLM
model = AutoModelForCausalLM.from_pretrained('/share/datasets/public_models/Llama-2-7b-chat-hf/')

[2024-10-10 11:01:48,321] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)


Loading checkpoint shards: 100%|██████████| 2/2 [00:02<00:00,  1.10s/it]


In [4]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('/share/datasets/public_models/Llama-2-7b-chat-hf/')

In [98]:
tokenizer.decode(435)

'J'

In [93]:
token

'Ult'

In [21]:
import torch

tensor_with_neg_inf = torch.tensor(float('-inf'))
print(tensor_with_neg_inf)

tensor(-inf)


In [26]:
neg_inf_tensor = torch.full((4, 4), float('-inf'))
print(neg_inf_tensor)

tensor([[-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf]])


In [38]:
data = torch.arange(2)

In [41]:
neg_inf_tensor[0,0:2] = data

In [42]:
neg_inf_tensor

tensor([[0., 1., -inf, -inf],
        [-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf]])

In [35]:
data = torch.zeros(1,3)

In [37]:
torch.nn.functional.pad(data)

TypeError: pad() missing 1 required positional arguments: "pad"

In [66]:
data = {0:[{0,1},{1}],2:[0]}

In [67]:
{1,2,3,4}  -{1,2}

{3, 4}

In [68]:
data[0][0]

{0, 1}

In [69]:
lst = [1,2,3]

In [80]:
a = torch.tensor(0)
data = torch.arange(12).reshape(1,12)

In [88]:
index = set()

In [89]:
type(index)

set

In [85]:
int(torch.where(data == a)[0])

0

In [99]:
data ={2,4,5}
b = {1,2,3,4,5}
a = b-data

In [132]:
a = torch.arange(10)
b = a

In [129]:
b[0] = 1

In [126]:
a[[0,3,4]] = b

In [139]:
id = set()

In [140]:
b = a[]

In [141]:
b[0] = 0

IndexError: index 0 is out of bounds for dimension 0 with size 0

In [24]:
import torch
a = torch.ones(1,1,4,10)
b = torch.zeros(1,1,8,20)

In [29]:
b[:,:,:,12:][:,:,[0,2,3,4],[0,2,3,4]]

tensor([[[0., 0., 0., 0.]]])

In [28]:
a

tensor([[[[1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.]]]])

In [34]:
b = a

In [35]:
b[0,0,0,0] = 0

In [36]:
a

tensor([[[[0., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
          [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.]]]])

In [39]:
a = {0}
a.union({1})

{0, 1}

In [40]:
a

{0}